// Stamps the current time as the "build version" into two places that
// must always agree:
//  - public/version.json  → served as a static file on the live site,
//                            fetched by the browser to check for updates.
//  - src/version.js        → bundled into the JS itself, so the running
//                            page knows what version *it* was built as.
//
// Runs automatically before `npm run dev` and `npm run build` (see the
// "predev"/"prebuild" scripts in package.json), so it's always fresh.
import { writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

const version = String(Date.now())

mkdirSync(join(root, 'public'), { recursive: true })
writeFileSync(join(root, 'public', 'version.json'), JSON.stringify({ version }))
writeFileSync(join(root, 'src', 'version.js'), `// Auto-generated by scripts/generate-version.js — do not edit by hand.\nexport const BUILD_VERSION = '${version}'\n`)

console.log(`[generate-version] stamped build version ${version}`)
